defaults:
  app:
    workerTypes: !env:json WORKER_TYPES
    project: !env GOOGLE_PROJECT
    provisionerId: !env PROVISIONER_ID
    credentialUrl: !env CREDENTIAL_URL
    audience: !env AUDIENCE

  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  monitoring:
    project: !env MONITORING_PROJECT
    enable: !env:bool MONITORING_ENABLE

  server:
    port: !env:number PORT
    env: !env NODE_ENV
    forceSSL: !env:bool FORCE_SSL
    trustProxy: !env:bool TRUST_PROXY
